# Generated by Django 3.2.25 on 2024-07-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_images/default.png', upload_to='news_images/')),
                ('link', models.URLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsoverview', to='yekatit.page')),
            ],
        ),
    ]
