# Generated by Django 3.2.25 on 2024-07-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0004_newsoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoverview',
            name='published_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='newsoverview',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
