# Generated by Django 3.2.25 on 2024-07-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0005_auto_20240729_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsoverview',
            name='link',
        ),
    ]
