# Generated by Django 3.2.25 on 2024-08-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0006_remove_newsoverview_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
