# Generated by Django 3.2.25 on 2024-08-09 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0008_auto_20240809_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_images/default.png', upload_to='announcement_images/')),
                ('published_date', models.DateField(default='2024-01-01')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='yekatit.page')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnouncementOverview',
        ),
    ]
