# Generated by Django 3.2.25 on 2024-09-03 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yekatit', '0011_announcement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoverview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
